
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"

required = [
    "github.com/alecthomas/gometalinter",
    "github.com/client9/misspell/cmd/misspell",
    "github.com/dnephin/govet",
    "github.com/golang/lint/golint",
    "github.com/gordonklaus/ineffassign",
    "github.com/jgautheron/goconst/cmd/goconst",
    "github.com/kisielk/errcheck",
    "honnef.co/go/tools/cmd/megacheck",
]

[[constraint]]
  name = "github.com/inconshreveable/log15"
  version = "2.11.0"

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "1.1.0"

[[constraint]]
  name = "gopkg.in/alecthomas/kingpin.v2"
  version = "2.2.5"

[[constraint]]
    name = "github.com/alecthomas/gometalinter"
    branch = "master"
