apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: hello
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello
        image: novas0x2a/hello:dev
        ports:
        - containerPort: 80
